services:
  apache:
    build:
      context: ./apache-php-lamp
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./prestashop_8.2.1:/app
      - ./apache-php-lamp/vhost-apache.conf:/etc/apache2/sites-enabled/install.conf
      - ./certificados:/certificados/
      #php.ini
    env_file:
      - ./.env.prod

