services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./prestashop_8.2.1:/app
      - ./certificados:/certificados
      - ./nginx-lemp/vhost-nginx.conf:/etc/nginx/conf.d/default.conf 
    env_file: 
      - ./.env.dev
    networks:
      redelamplemp:
        aliases:
          - test.lan

  phpserver:
    build: php-lemp
    volumes:
      - ./prestashop_8.2.1:/app
      - ./certificados:/certificados 
      - ./php-lemp/www.conf:/etc/php/8.1/fpm/pool.d/www.conf
    env_file: 
      - ./.env.dev
    networks:
      redelamplemp:

  basededatos:
    image: mysql:latest
    env_file: 
      - ./.env.dev
    volumes:
      - data:/var/lib/mysql
      - ./basededatos/:/scripts/
    networks:
      redelamplemp:

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    networks:
      redelamplemp:
    environment:
      - PMA_HOST=basededatos

volumes:
  data:

networks:
  redelamplemp: