<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3TgaYUo\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3TgaYUo/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container3TgaYUo.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container3TgaYUo\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container3TgaYUo\appAppKernelProdContainer([
    'container.build_hash' => '3TgaYUo',
    'container.build_id' => '2d1b9c0a',
    'container.build_time' => 1742033693,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3TgaYUo');
